set_property IOSTANDARD LVCMOS33 [get_ports o_and]
set_property IOSTANDARD LVCMOS33 [get_ports o_nand]
set_property IOSTANDARD LVCMOS33 [get_ports o_nor]
set_property IOSTANDARD LVCMOS33 [get_ports o_or]
set_property IOSTANDARD LVCMOS33 [get_ports o_xnor]
set_property IOSTANDARD LVCMOS33 [get_ports o_xor]
set_property PACKAGE_PIN D18 [get_ports o_and]
set_property PACKAGE_PIN E17 [get_ports o_or]
set_property PACKAGE_PIN L19 [get_ports o_xnor]
set_property PACKAGE_PIN G19 [get_ports o_xor]

set_property PACKAGE_PIN J19 [get_ports o_nand]
set_property PACKAGE_PIN K16 [get_ports o_nor]

set_property PACKAGE_PIN M20 [get_ports i_a]
set_property PACKAGE_PIN G20 [get_ports i_b]
set_property IOSTANDARD LVCMOS33 [get_ports i_a]
set_property IOSTANDARD LVCMOS33 [get_ports i_b]
