# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_buttons_0/system_buttons_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_buttons_0 || ORIG_REF_NAME==system_buttons_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_xbar_0/system_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==system_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_100M_1/system_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_1 || ORIG_REF_NAME==system_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_0/system_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_buttons_0/system_buttons_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_buttons_0 || ORIG_REF_NAME==system_buttons_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_buttons_0/system_buttons_0_ooc.xdc

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_buttons_0/system_buttons_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_buttons_0 || ORIG_REF_NAME==system_buttons_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_1/system_rst_ps7_0_100M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_1 || ORIG_REF_NAME==system_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_1/system_rst_ps7_0_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_1 || ORIG_REF_NAME==system_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_interconnect_0_imp_auto_pc_0/system_axi_interconnect_0_imp_auto_pc_0_ooc.xdc

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab2/edt_zc702/edt_zc702.gen/sources_1/bd/system/system_ooc.xdc
