# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab1/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab1/edt_zc702/edt_zc702.gen/sources_1/bd/system/system_ooc.xdc
