# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab3/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_master_pl_0_0/system_axi_master_pl_0_0.xci
# IP: The module: 'system_axi_master_pl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab3/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_master_pl_0_0/constraints/axi_master_pl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_master_pl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab3/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_master_pl_0_0/system_axi_master_pl_0_0.xci
# IP: The module: 'system_axi_master_pl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab1/MicroPhase-Z7-Lite-Board/examples/idec/lab3/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_master_pl_0_0/constraints/axi_master_pl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_master_pl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
