domain_path: C:\lab1\MicroPhase-Z7-Lite-Board\examples\idec\lab2\edt_zc702_workspace\edt_zc702\export\edt_zc702\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
